apiVersion: batch/v1
kind: Job
metadata:
  name: generate-article
  labels:
    app: generate-article
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
        - name: generate-article
          image: ghcr.io/liubin95/liubin/generate-article
          env:
            - name: MYSQL_HOST
              value: mysql-service.default.svc.cluster.local
      restartPolicy: Never


