kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: default

resources:
- ./cluster.yml
- ./client.yaml

configMapGenerator:
- name: definitions
  files:
  - ./config/definitions.json

generatorOptions:
  disableNameSuffixHash: true
