apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es
  namespace: liubin
spec:
  version: 7.14.0
  nodeSets:
    - name: es-cluster
      count: 3
      config:
        node.store.allow_mmap: false
        ingest.geoip.downloader.enabled: false
        xpack.security.enabled: true # enable xpack security
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              image: ghcr.io/liubin95/liubin/elasticsearch


