apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: liubin
  labels:
    app: es

spec:
  selector:
    matchLabels:
      app: es
  serviceName: es-service
  replicas: 3
  template:
    metadata:
      labels:
        app: es
    spec:
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-pvc
        - name: es-config
          configMap:
            name: es-config
        - name: es-certs
          secret:
            secretName: my-pass
      containers:
        - name: es
          image: ghcr.io/liubin95/liubin/elasticsearch:1.0.2
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-pass
                  key: comm-pass
            - name: CERTS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-pass
                  key: elasticsearch-certs-password
            - name: TAKE_FILE_OWNERSHIP
              value: "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              name: es-config
              readOnly: true
            - mountPath: /usr/share/elasticsearch/config/jvm.options
              subPath: jvm.options
              name: es-config
              readOnly: true
            - mountPath: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
              name: es-certs
              readOnly: true
              subPath: elastic-certificates.p12


