apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: liubin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
