apiVersion: v1
kind: Service
metadata:
  name: es-service
  namespace: liubin
spec:
  clusterIP: None
  selector:
    app: es
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
