# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.30.2
imageRepository: registry.aliyuncs.com/google_containers
networking:
  #podSubnet和serviceSubnet通常设置为不重叠的网段,以防止IP地址冲突。
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
# 默认值
cgroupDriver: systemd
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
