apiVersion: v1
kind: Pod
metadata:
  name: kafka-single-node
  labels:
    name: kafka-single-node
spec:
  containers:
  - name: kafka
    image: bitnami/kafka:latest
    ports:
    - containerPort: 9092
    - containerPort: 9093
    env:
    - name: KAFKA_CFG_NODE_ID
      value: "0"
    - name: KAFKA_CFG_PROCESS_ROLES
      value: "controller,broker"
    - name: KAFKA_CFG_LISTENERS
      value: "PLAINTEXT://:9092,CONTROLLER://:9093"
    - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
      value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka-single-node-service.default.svc.cluster.local:9092"
    - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
      # kafka-single-node-service.default.svc.cluster.local:9093
      value: "0@kafka-single-node-service.default.svc.cluster.local:9093"
    - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
      value: "CONTROLLER"
    readinessProbe:
      tcpSocket:
        port: 9092
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      tcpSocket:
        port: 9092
      initialDelaySeconds: 15
      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-single-node-service
  labels:
    name: kafka-single-node-service
spec:
  selector:
    name: kafka-single-node
  ports:
  - port: 9092
    name: kafka
    targetPort: 9092
  - port: 9093
    name: controller
    targetPort: 9093
