# https://hub.docker.com/r/nicolaka/netshoot
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
spec:
  containers:
  - name: netshoot
    image: docker.io/nicolaka/netshoot:latest
    command: ["sleep", "3600"]
