apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  nameSpace: liubin
  labels:
    app: mysql

spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-master-config
          configMap:
            name: mysql-master-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: ghcr.io/liubin95/liubin/mysql
          volumeMounts:
            - name: mysql-master-config
              mountPath: /etc/mysql/mysql.conf
              subPath: mysql.conf
              readOnly: true
            - name: mysql-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-pass
                  key: mysql-pass
