apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql

spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-master-config
          configMap:
            name: mysql-master-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: ghcr.io/liubin95/liubin/mysql
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-master-config
              mountPath: /etc/mysql/mysql.conf
              subPath: mysql.conf
            - name: mysql-data
              mountPath: /var/lib/mysql
          envFrom:
            - secretRef:
                name: mysql-pass

