apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  nameSpace: liubin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
