apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: liubin
  labels:
    app: es

data:
  elasticsearch.yml: |
    cluster:
      name: es-cluster
    network:
      bind_host: 0.0.0.0
      publish_host: ${POD_IP}
    http:
      port: 9200
      cors:
        enabled: true
        allow-origin: "*" # CORS allowed origin
    bootstrap:
      memory_lock: false
      system_call_filter: false
    ingest.geoip.downloader.enabled: false # disable geoip downloader
    xpack.security.enabled: true # enable xpack security
    
    discovery.seed_hosts: 
      - "es-0.es-service.liubin.svc.cluster.local"
      - "es-1.es-service.liubin.svc.cluster.local"
      - "es-2.es-service.liubin.svc.cluster.local"
    cluster.initial_master_nodes: 
      - "es-0"
      - "es-1"
      - "es-2"

  jvm.options: |
    -Xms512m
    -Xmx512m
    -XX:+UseParallelGC
