apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: liubin
  labels:
    app: mysql

data:
  master.cnf: |
    [mysqld]
    # 主服务器唯一ID
    server-id=1
    # 启用二进制日志
    log-bin=mysql-bin
    # 解析模式
    binlog_format = row
    # 设置需要复制的数据库(可设置多个)
    binlog-do-db=big_three
    # 启用 GTID 模式
    gtid_mode=ON
    # 启用 GTID 模式
    enforce-gtid-consistency=ON
    sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

  slave.cnf: |
    [mysqld]
    # 从服务器唯一ID
    server-id=2
    # 启用 GTID 模式
    gtid_mode=ON
    # 启用 GTID 模式
    enforce-gtid-consistency=ON
    # 副本服务器上禁用二进制日志记录
    log-slave-updates=OFF
    sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
